---
title: 'Tech Guide: GitHub'
author: "STAT 5400"
date: "Nov 13, 2020."
output:
  md_document:
    df_print: paged
  html_document:
    df_print: paged
  pdf_document: default
---

This document is a simplified version of <https://github.com/jfiksel/github-classroom-for-students>, written by Jacob Fiksel. This document is also adapted from <https://happygitwithr.com>. This video is helpful: <https://www.youtube.com/watch?v=pAcMgGbCtQw&feature=youtu.be>.

## Getting setup with GitHub
1. Register for an account on GitHub (https://github.com/). Please use a username that contains your identification information.
2. Install Git. See (https://happygitwithr.com/install-git.html).
  * Windows: Install Git for Windows (https://gitforwindows.org/). 
  * Mac: install Xcode command line tools. Go to terminal (Applications -> Utilities -> Terminal), type:
  
      ```
  git --version
  git config
  ```
  
3. Configure GitHub.  
  You can type in Shell:
    
     ```
  git config --global user.name 'Stat Student'
  git config --global user.email 'stat-student@uiowa.edu'
  ```
  You may also do this using an R package:
  
      ```{r eval=FALSE}
  ## install.packages("usethis")
  library(usethis)
  use_git_config(user.name = "Stat Student", user.email = "stat-student@uiowa.edu")
  ```

  4. Set up SSH keys. Here is a very detailed instruction. <https://happygitwithr.com/ssh-keys.html>. You may skip this step until you are familiar with GitHub.
  
  
## Downloading and editing homework from GitHub
1. In your computer, make a directory like STAT5400 and make a subdirectory called HW.
2. Accept your assignment. Try the test link: <https://classroom.github.com/a/P0agrYYx>.
3. Enter the homework repository on GitHub and clich "Clone or Download". You have copied <https://github.com/STAT5400-20Fall/GitHub-Instruction.git> in your clipboard.
4. In Rstudio, go to File -> New Project, and then click Version Control, and then Git. Paste the link you just copied, and create this as a subdirectory of the folder HW. Now you should see a list of the files in Rstudio. You can click on the file you want to edit and make changes. Click the .Rproj file if you leave and go back to continue your project. 
5. Commit these changes to your local repository. CLick the Git tab and check the file you want to commit. Click commit and type a message in "Commit message" such as "Added a comment line". Click "Commit".
6. Click the green "Push" botton to send your local changes to GitHub.



Besides Rstudio, you can also use Git through Shell, or use some other clients, like GitHub Desktop, SmartGit, etc.
